version: "3.7"

services:
  web:
    container_name: web
    env_file: ./backend/web/.env
    build: ./backend/web/.
    volumes:
      - ./backend/web:/code/
      - static_volume:/code/staticfiles # <-- bind the static volume
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 config.wsgi:application
    networks:
      - backend_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=config.local_settings
    depends_on:
      - db
  backend-server:
    container_name: nginx-back
    build:
      context: ./backend/nginx/.
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/code/staticfiles # <-- bind the static volume
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - backend_network
  db:
    container_name: db
    image: mariadb:10.7.1
    #build: ./mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33306:3306"
    env_file: ./mariadb/master/.env
    environment:
      TZ: 'Asia/Seoul'
    volumes:
      - ./mariadb/master/config/:/etc/mysql/conf.d
      - ./mariadb/master/volume:/var/lib/mysql
      - ./mariadb/master/sql/:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    restart: always # <-- always running...

  db_slave:
    container_name: db_slave
    image: mariadb:10.7.1
    #build: ./mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "43306:3306"
    env_file: ./mariadb/slave/.env
    environment:
      TZ: 'Asia/Seoul'
    volumes:
      - ./mariadb/slave/config/:/etc/mysql/conf.d
      - ./mariadb/slave/volume:/var/lib/mysql
      - ./mariadb/slave/sql/:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    restart: always # <-- always running...
    links:
      - db
      
networks:
  backend_network:
    driver: bridge
volumes:
  static_volume:
